### ISSUE TITLE
uh1tk2 - Definición del Alcance del Proyecto

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#12]
Objetivo: Definir el alcance del proyecto y los objetivos generales durante la reunión.

Descripción del Proyecto:
Desarrollar un sistema de control y monitoreo distribuido para optimizar el uso y gestión del agua en diferentes entornos. Este controlador, tipo célula, es capaz de abarcar el control general y amplio de jardines, plazas, huertas urbanas, así como grandes plantaciones agrícolas en campos rurales. El sistema se enfoca en la eficiencia y sostenibilidad del riego mediante la gestión y monitoreo inteligente de los recursos hídricos locales.

Objetivos 
-Funcionamiento del Sistema
-Transmisión de Datos
-Procesamiento de Datos
-Toma de Decisiones y Actuación
-Visualización y Monitoreo

**Comment by diegote7** [comment]
se completa tarea
