### ISSUE TITLE
uh1tk3 - Asignación de Roles y Responsabilidades

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#13]
Objetivo: Asignar roles y responsabilidades a los miembros del equipo.

Responsabilidades:

Scrum Master: 
-Facilitación de flujos de trabajo: El Scrum Master configura y gestiona proyectos en GitHub, utilizando herramientas como GitHub Projects y GitHub Actions para automatizar y visualizar flujos de trabajo.
-Gestión de issues y pull requests: Ayuda a mantener el tablero de proyectos y asegura que los issues y pull requests estén alineados con las prioridades del sprint.
-Monitoreo de progreso: Utiliza gráficos de burndown o velocity, generados en GitHub, para monitorear el progreso del sprint.
-Resolución de impedimentos: Colabora en GitHub Discussions o en issues para resolver problemas y bloqueos que enfrenta el equipo.
-Responsables: Patricio Leandro roldan, Diego Ezequiel Ares

Product Owner:
-Gestión del Product Backlog: El Product Owner gestiona el backlog directamente en GitHub creando, priorizando y organizando los issues y epics en función del valor de negocio.
-Definición de criterios de aceptación: Añade detalles y criterios de aceptación a cada issue o pull request, asegurando que el equipo de desarrollo entienda claramente las expectativas.
-Revisión de entregables: Revisa y aprueba pull requests, asegurándose de que el trabajo cumpla con los requisitos y criterios de aceptación antes de ser fusionado en la rama principal.
-Comunicación con stakeholders: Utiliza GitHub para comunicar el estado del proyecto a los stakeholders, compartiendo tableros y milestones para mantener la transparencia.
-Responsables: Luciano Lujan, rodo Paz

Desarrollo: 
-Desarrollo colaborativo: Trabajan en ramas de Git para desarrollar nuevas funcionalidades, solucionar bugs, y mejorar el código, utilizando pull requests para revisar y discutir los cambios.
-Integración continua: Implementan pipelines de integración continua (CI) con GitHub Actions para automatizar pruebas, compilaciones y despliegues.
-Gestión de issues: El equipo trabaja en issues asignados y utiliza GitHub Projects para planificar y organizar el trabajo dentro de un sprint.
-Documentación en código: Mantienen la documentación del código y los procesos de desarrollo en el repositorio, usando README.md, CONTRIBUTING.md, y otros archivos.
-Responsables: Nahuel Velez, vittorio durigutti, Raul Jara, Marcos Bordon Rios, Nicolas Barrionuevo, Lisandro juncos, Fernando Gimenez. 

Documentacion: 
-Documentación del proyecto: Se crea y mantiene en archivos markdown (.md) dentro del repositorio, como README.md, que proporciona una visión general del proyecto.
-Wiki y GitHub Pages: Utilizan la wiki de GitHub o GitHub Pages para proporcionar documentación más detallada y estructurada, accesible tanto para el equipo como para los usuarios.
-Documentación de procesos: Crean documentos que describen los flujos de trabajo de desarrollo, las guías de contribución y los estándares de código, asegurando que todos los miembros del equipo sigan las mismas prácticas.
-Historial de cambios: Mantienen un registro de cambios detallado en el archivo CHANGELOG.md para rastrear la evolución del proyecto a lo largo del tiempo.
-Responsables: Nahuel Velez, vittorio durigutti, Marcos Bordon Rios, Jazmin Barbero, Tiziano paez, Macarena Carballo, Laura brizuela, Fermando Gimenez.

**Comment by diegote7** [comment]
se completa tarea
