### ISSUE TITLE
uh1tk5 - Investigación del Protocolo de Comunicación MQTT

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#15]
Objetivo: Investigar el protocolo de comunicación MQTT.

Descripcion del protocolo
Caracteristicas principales
Aplicaciones comunes
Ventajas y desventajas

**Comment by marquezjose** [comment]
##  Investigar el protocolo de comunicación MQTT.

### Definición y Propósito:  

#### MQTT (Message Queuing Telemetry Transport):

**Tipo de Tecnología:**  
- MQTT es un protocolo de mensajería basado en el modelo publicador/suscriptor.  
  
- Propósito: Facilita la transmisión de mensajes entre dispositivos IoT y servidores (brokers) de manera eficiente y en tiempo real. Es especialmente útil en redes con conexiones inestables o anchos de banda limitados.  

**Uso Típico:**  
-  Comunicación entre sensores, dispositivos IoT y aplicaciones de backend, gestión de mensajes en sistemas IoT, automatización del hogar.

**Comment by NicolasBa27** [comment]
Investigación  sobre el protocolo MQTT.
