### ISSUE TITLE
uh1tk6 - Informe de Investigación de Protocolos de Comunicación

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#16]
Objetivo: Documentar los hallazgos de la investigación en un informe.

Introducción: [Breve introducción sobre el propósito del informe]

Metodología: [Descripción de cómo se llevó a cabo la investigación]

Resultados:
- LoRa: [Resumen de los hallazgos sobre LoRa]
- MQTT: [Resumen de los hallazgos sobre MQTT]

Conclusiones: [Conclusiones generales de la investigación]

Recomendaciones: [Recomendaciones basadas en los hallazgos]

**Comment by marquezjose** [comment]
## Documentar los hallazgos de la investigación en un informe.  
  
**- Tener en cuenta, caratula acorde al instituto, incluyendo: materia, integrantes y por lo indicado por el profesor, los formatos sugeridos son Markdown (menos práctico para agregar imagenes) o PDF.**

**Comment by RoHu17** [comment]
Tarea Terminada.
