### ISSUE TITLE
uh3tk 2 - Configuración de módulos Bluetooth en el ESP32

### ISSUE THREAD

**Issue by vittoriodurigutti** [ISPC-TST-FP-2024/proyecto-CGRH#164]
### uh3tk 2 - Configuración de módulos Bluetooth en el ESP32

**Objetivos**:

- Configurar la funcionalidad de Bluetooth Low Energy (BLE) en el ESP32.
- Permitir la comunicación básica a través de Bluetooth (enviar y recibir datos).
- Crear una interfaz para emparejar dispositivos Bluetooth desde el ESP32.
- Establecer un sistema de control del dispositivo (LEDs, actuadores) mediante comandos Bluetooth.

**Tareas**:

- [x] Configurar el ESP32 como dispositivo Bluetooth que pueda ser detectado por otros dispositivos.
- [x] Implementar un menú para controlar la activación y desactivación del módulo Bluetooth.
- [x] Desarrollar un sistema de emparejamiento que permita conectar dispositivos a través de un PIN.
- [x] Programar la capacidad de recibir datos y controlar dispositivos conectados (por ejemplo, encender/apagar LEDs).
- [x] Implementar la funcionalidad para enviar datos a otros dispositivos mediante comandos Bluetooth.
- [ ] Integrar el manejo de múltiples conexiones y gestión de errores de emparejamiento.

**Comment by diegote7** [comment]
se configura  la funcionalidad de Bluetooth Low Energy (BLE)

**Comment by diegote7** [comment]
s completa parte de la tarea

**Comment by diegote7** [comment]
se completa la tarea
