### ISSUE TITLE
uh1tk7 - Identificación de Variables Ambientales Relevantes

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#17]
Objetivo: Identificar y listar las variables ambientales relevantes.

Detalles:

- Lista de Variables: (Humedad del suelo, pH ,Lluvia ,Temperatura, etc)

- Descripción de Cada Variable: (ejemplo)
  - Humedad del suelo: [Descripción]
  - pH: [Descripción]
  - Lluvia: [Descripción]
  - Temperatura: [Descripción]

**Comment by MacarenaAC** [comment]
Actividad realizada.
