### ISSUE TITLE
uh1tk17 - Configuración de Ramas en el Repositorio

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#27]
Objetivo: Configurar el repositorio con las ramas necesarias.

Detalles:

- Ramas Iniciales:
  - main: [Descripción]
  - develop: [Descripción]
  - [Otras ramas necesarias]
- Política de Ramas: [Descripción de la política de ramas]

**Comment by marquezjose** [comment]
## Configurar el repositorio con las ramas necesarias (main, develop, etc.).

**Comment by vittoriodurigutti** [comment]
Se crean y configuran las ramas de Documentacion y Desarrollo
