### ISSUE TITLE
uh1tk18 - Definición y Documentación de la Convención de Commits y Ramas

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#28]
Objetivo: Definir y documentar la convención de commits y ramas.

Detalles:

- Convención de Commits: [Descripción de la convención de commits]
- Convención de Ramas: [Descripción de la convención de ramas]
- Documento de Referencia: [Enlace o ubicación del documento]

**Comment by marquezjose** [comment]
## Definir y documentar la convención de commits y ramas.

**Comment by vittoriodurigutti** [comment]
Se establece y configura en cada tarjeta la la rama con formato: uh(n)tk(n)
Se establece cada rama sobre la rama correspondiente: Desarrollo o Documentacion
Se establece convención para realización de commits
