### ISSUE TITLE
uh1tk19 - Documentación de Roles y Responsabilidades

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#29]
Objetivo: Documentar claramente los roles y responsabilidades asignados.

Detalles:

- Lista de Roles y Responsabilidades:
  - [Rol 1]: [Descripción de responsabilidades]
  - [Rol 2]: [Descripción de responsabilidades]
  - [Rol 3]: [Descripción de responsabilidades]

**Comment by marquezjose** [comment]
## Documentar claramente los roles y responsabilidades asignados.

**Comment by FerCbr** [comment]
## Tarea correspondiente a la Historia de Usuario uh#1:  
  "Establecimiento de roles y responsabilidades del equipo".    

## *uh1tk19:* "Documentar claramente los roles y responsabilidades asignados."  

Se agregara al Readme principal un gráfico documentando los roles asignados.
