### ISSUE TITLE
uh1tk20 - Comunicación de Roles y Responsabilidades

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#30]
Objetivo: Comunicar los roles y responsabilidades a todos los miembros del equipo.

Detalles:

- Método de Comunicación: [Reunión, correo electrónico, etc.]
- Fecha de Comunicación: [Fecha]

**Comment by marquezjose** [comment]
## Comunicar los roles y responsabilidades a todos los miembros del equipo.

**Comment by lucianoilujan** [comment]
Esta tarea está completa. 
El medio de comunicación fue establecido por WhatsApp.
Los roles fueron ya anunciados.
