### ISSUE TITLE
uh1tk1 - Reunion inical 

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#31]
Objetivo: Establecer los objetivos del proyecto, roles y responsabilidades, y planificar las próximas acciones.

Detalles: 
- Fecha y Hora: [Especificar la fecha y hora de la reunión]
- Lugar: [Especificar el lugar o el enlace de la reunión virtual]
- Participantes: [Lista de todos los miembros del equipo]

**Comment by pleroldan** [comment]
## Log1

- Fecha y Hora: Reuninon inicial dia 17/08/2024 a las 22:00 UTC-3  
- Lugar: Meet https://meet.google.com/icw-pdiw-qwy
