### ISSUE TITLE
uh1tk23 - Creación de Cronograma Detallado

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#35]
Objetivo: Crear un cronograma detallado con fechas de los hitos.

Detalles:

- Método: Herramienta de gestión de proyectos (el mismo Github Proyect. Podemos crear un tablero distinto con linea de fechas.)
- Fecha: [Fecha]

**Comment by pleroldan** [comment]
Se crea cronograma y se aplica en kanban. Se aguarda revision y coordinar posibles cambios
