### ISSUE TITLE
uh1tk24 - Validación del Cronograma

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#36]
Objetivo: Validar el cronograma con los stakeholders.

Detalles:

- Método: Reunión con stakeholders
- Fecha: [Fecha]

**Comment by lucianoilujan** [comment]
Se intentó cumplir con las validaciones del cronograma sin la herramienta de roadmap. No estuvo fácil, por eso en el segundo sprint se implementó la hoja de ruta para poder complicar con los tiempos requierodo.
