### ISSUE TITLE
uh1tk26 - Configuración de Herramientas de Comunicación

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#38]
Objetivo: Configurar las herramientas y asegurarse de que todos los miembros tengan acceso.

Detalles:

- Método: Configuración técnica y pruebas de acceso
- Fecha: [Fecha]

**Comment by pleroldan** [comment]
Herramientas a Utilizar
WhatsApp: Se utilizará para la organización general del equipo, la comunicación rápida y la coordinación de tareas.
Google Meet: Se utilizará para realizar reuniones diarias y reuniones más formales, permitiendo la colaboración en tiempo real y la compartición de pantalla.
