### ISSUE TITLE
uh1tk28 - Configuración de Tablero Kanban

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#40]
Objetivo: Configurar un tablero Kanban en una herramienta acorde.

Detalles:

- Herramienta Seleccionada: Github Proyect
- Pasos para Configuración:
  - Crear un nuevo tablero
  - Definir columnas (e.g., To Do, In Progress, Done)
  - Personalizar el tablero según las necesidades del proyecto

**Comment by vittoriodurigutti** [comment]
Se crea tablero  - TAREAS - 
Se definen columnas:
 - Spring Backlog: Se crearan los spring con el cumulo de tareas y resultados esperados. Tareas definididas segun el formato uh(nro sprint)tk(nro de tarea dentro del sprint)
 - To Do - Sprint (nro de sprint): Se listan las tareas, generando los issues correspondientes. Asignacion manual segun la division de tareas.
 - Progress:
