### ISSUE TITLE
uh1tk29 - Organización de Tareas del Sprint en Tablero Kanban

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#41]
Objetivo: Organizar las tareas del sprint en el tablero Kanban.

Detalles:
- Lista de Tareas:
  - Definidas en detalle en Sprint Backlog - Sprint 1
- Asignación a Columnas:
  - To Do: [Tareas pendientes]
  - In Progress: [Tareas en progreso]
  - Done: [Tareas completadas]

**Comment by vittoriodurigutti** [comment]
Una vez realizado la configuracion y personalizacion del tablero, Se definieron y crearon las tareas compuestas del siguiente formato:
Titulo:
Objetivo:
Detalles: 

Se actualizan comentarios ante futuras modificaciones.
