### ISSUE TITLE
uh1tk30 -  Asignación de Tareas a Miembros del Equipo

### ISSUE THREAD

**Issue by marquezjose** [ISPC-TST-FP-2024/proyecto-CGRH#42]
Objetivo: Asignar las tareas a los miembros del equipo.

Detalles:

- Lista de Tareas y Asignaciones:
  - [Tarea 1]: [Nombre del miembro del equipo]
  - [Tarea 2]: [Nombre del miembro del equipo]
  - [Tarea 3]: [Nombre del miembro del equipo]
- Responsabilidades de Cada Miembro: [Descripción de las responsabilidades]

**Comment by lucianoilujan** [comment]
Se asignaron tareas en el diferente áreas.
