### ISSUE TITLE
uh2tk22: Integración de comunicación en el software del proyecto

### ISSUE THREAD

**Issue by vittoriodurigutti** [ISPC-TST-FP-2024/proyecto-CGRH#84]
Objetivos:

- Integrar los módulos de comunicación en el software principal del proyecto.
- Asegurarse de que la comunicación funcione en conjunto con otras funcionalidades del software.
- Probar la integración y realizar ajustes si es necesario.

Subtareas/Pasos:

- [ ] Revisar el código base del proyecto para planificar la integración.
- [ ] Añadir las funciones de comunicación (WiFi, Bluetooth) en el software principal.
- [ ] Probar la integración del software y los módulos de comunicación.
- [ ] Resolver problemas de compatibilidad o conflictos entre funcionalidades.
- [ ] Documentar el proceso de integración y las pruebas realizadas.

**Comment by diegote7** [comment]
se crean los archivos para resolver los siguientes puntos                                                                                               communication_module.py:

Define una clase base CommunicationModule que actúa como interfaz para cualquier tipo de comunicación.
Las clases BLECommunication y WiFiCommunication implementan la funcionalidad específica para Bluetooth y Wi-Fi respectivamente.
strategy.py:

Implementa el patrón Strategy para seleccionar el protocolo de comunicación dinámicamente.
Dependiendo del tipo de comunicación (BLE o Wi-Fi), instancia la clase adecuada para manejar la comunicación.
main.py:

Este archivo es el punto de entrada del proyecto. Se selecciona el tipo de comunicación deseado (en este caso, WiFi) y se utiliza para conectarse, enviar y recibir datos.
exceptions.py:

Archivo opcional que define excepciones específicas para gestionar errores que puedan surgir en la comunicación. Se puede expandir para manejar errores de forma más precisa.

**Comment by diegote7** [comment]
se completa tarea
